name: tests
on:  [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Unit tests
        run: |
          TF_ACC=1 go test -mod=vendor ./... -v -trimpath -coverprofile=coverage.out
          go tool cover -func=coverage.out


